Efarming/urls.py
from django.contrib import admin
from django.urls import path

from farmerapp.payment import original_payment, payment_status
from farmerapp.views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name="home"),
    path('signup',Signup,name="signup"),
	path('about/',About,name='about'),
	path('contact/',Contact,name='contact'),
    path('login/',Login,name="login"),
    path('logoutuser',Logout,name="logout"),
    path('view_user',View_user,name="view_user"),
    path('add_product',Add_Product,name="add_product"),
    path('view_feedback', View_feedback, name='view_feedback'),
    path('view_product(?P<int:pid>)', View_prodcut, name='view_product'),
    path('admin_view_product', Admin_View_product, name='admin_view_product'),
    path('login_admin',Admin_Login,name="login_admin"),
    path('admin_viewBooking', Admin_View_Booking, name='admin_viewBooking'),
    path('view_categary/', View_Categary, name='view_categary'),
    path('add_categary', Add_Categary, name='add_categary'),
    path('add_cart(?P<int:pid>)', Add_Cart, name='add_cart'),
    path('delete_product(?P<int:pid>)', delete_product, name='delete_product'),
    path('delete_user(?P<int:pid>)', delete_user, name='delete_user'),
    path('delete_feedback(?P<int:pid>)', delete_feedback, name='delete_feedback'),
    path('cart', view_cart, name='cart'),
    path('payment(?P<book>[0-9]+)', payment, name='payment'),
    path('delete_booking/(?P<str:pid>)/(?P<bid>[0-9]+)', delete_booking, name='delete_booking'),
    path('delete_admin_booking/(?P<str:pid>)/(?P<bid>[0-9]+)', delete_admin_booking, name='delete_admin_booking'),
    path('booking_detail/(?P<str:pid>)/(?P<bid>[0-9]+)', booking_detail, name='booking_detail'),
    path('admin_booking_detail/(?P<str:pid>)/(?P<bid>[0-9]+)/(?P<uid>[0-9]+)', admin_booking_detail, name='admin_booking_detail'),
    path('Edit_status/(?P<str:pid>)/(?P<bid>[0-9]+)', Edit_status, name='Edit_status'),
    path('remove_cart(?P<int:pid>)', remove_cart, name='remove_cart'),
    path('booking(?P<str:pid>)', Booking_order, name="booking"),
    path('view_booking', View_Booking, name='view_booking'),
    path('profile/<int:pid>', profile, name='profile'),
    path('edit_profile', Edit_profile, name='edit_profile'),
    path('delete_category(?P<int:pid>)', delete_category, name='delete_category'),
    path('admin_home', Admin_Home, name='admin_home'),
    path('change_password', Change_Password, name="change_password"),
    path('payment_status/', payment_status, name="payment_status"),
    path('original_payment/', original_payment, name="original_payment"),
    path('view_farmer/', View_farmer, name="view_farmer"),
    path('change_user_status/<int:pid>', change_user_status, name="change_user_status"),
    path('send_feedback/(?P<pid>[0-9]+)', Feedback, name='send_feedback'),
    path('product_detail/<int:pid>', product_detail, name='product_detail'),
    path('farmer_detail/<int:pid>', farmer_detail, name='farmer_detail'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmerapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    image = models.FileField(null=True)
    name = models.CharField(max_length=30, null=True)
    price = models.IntegerField(null=True)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.category.name+"--"+self.name

class Status(models.Model):
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    city = models.CharField(max_length=30, null=True)
    address = models.CharField(max_length=50, null=True)
    user_type = models.CharField(max_length=10, null=True)
    status =  models.CharField(max_length=30, null=True, default="Pending")
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username


class Cart(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.profile.user.username + " . " + self.product.name


class Booking(models.Model):
    status = models.ForeignKey(Status, on_delete=models.CASCADE, null=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    farmer =  models.TextField(null=True)
    booking_id = models.CharField(max_length=200,null=True)
    quantity = models.CharField(max_length=100,null=True)
    # quantity_json = models.JSONField(null=True,default=dict)
    payment_id = models.CharField(max_length=200,null=True)
    payment_status = models.CharField(max_length=200,null=True, default="Pending")
    book_date = models.CharField(max_length=30, null=True)
    total = models.IntegerField(null=True)

    def __str__(self):
        return self.book_date+" "+self.profile.user.username



class Send_Feedback(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    message1 = models.TextField(null=True)
    date = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.profile.user.username

farmerapp/views.py
from random import shuffle, random
from django.contrib import messages
from instamojo_wrapper import Instamojo
from django.db.models import Q
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout,login
from .models import *
from django.conf import settings
from django.utils.datastructures import MultiValueDictKeyError
from datetime import date
# Create your views here.

def Home(request):
    search = request.GET.get('search',0)
    search_pro = Product.objects.filter(Q(name__icontains = search) | Q(category__name__icontains = search))
    cat = ""
    pro = ""
    cat = ""
    num = 0
    num1 = 0
    cat = Category.objects.all()
    pro = Product.objects.all()
    num = []
    num1 = 0
    product = None
    try:
        user = User.objects.get(id=request.user.id)
        profile = Profile.objects.get(user=user)
        cart = Cart.objects.filter(profile=profile)
        product = recommended_product(request)
        for i in cart:
            num1 += 1

    except:
        pass
    a = 1
    li = []

    for j in pro:
        b = 1
        for i in cat:
            if i.name == j.category.name:
                if not j.category.name in li:
                    li.append(j.category.name)
                    if b == 1:
                        num.append(a)
                        b = 2
        a += 1


    d = {'pro': pro, 'cat': cat,'num':num,'num1':num1, 'product':product, 'search_pro':search_pro}
    return render(request, 'all_product.html', d)
	

def About(request):
    return render(request, 'about.html')

def Contact(request):
    return render(request, 'contact.html')	
	
	
# def Signup(request):
#     if request.method == 'POST':
#         u = request.POST['uname']
#         f = request.POST['fname']
#         l = request.POST['lname']
#         p = request.POST['pwd']
#         c = request.POST['city']
#         ad = request.POST['add']
#         e = request.POST['email']
#         i = request.FILES['img']
#         t = request.POST['type']
#         user = User.objects.create_user(username=u, email=e, password=p, first_name=f,last_name=l)
#         Profile.objects.create(user=user, city=c, address=ad,image=i, user_type=t)
#         messages.success(request, "Registeration Successfully")
#         return redirect('login')
#     return render(request, 'signup.html')
def Signup(request):
    if request.method == 'POST':
        try:
            u = request.POST['uname']
            f = request.POST['fname']
            l = request.POST['lname']
            p = request.POST['pwd']
            c = request.POST['city']
            ad = request.POST['add']
            e = request.POST['email']
            i = request.FILES['img']  # This line may cause MultiValueDictKeyError
            t = request.POST['type']

            user = User.objects.create_user(username=u, email=e, password=p, first_name=f,last_name=l)
            Profile.objects.create(user=user, city=c, address=ad, image=i, user_type=t)
            messages.success(request, "Registration Successful")
            return redirect('login')
        
        except MultiValueDictKeyError:
            # Handle the case where 'img' key is not found in request.FILES
            messages.error(request, "enter all the fields")
            return redirect('signup')

    return render(request, 'signup.html')


def Login(request):
    if request.method == "POST":
        u = request.POST['uname']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        if not user.is_staff and user:
            profile = Profile.objects.get(user=user)
            if profile.user_type == "Seller" and profile.status == "Approved":
                login(request, user)
                messages.success(request, "Logged in Successfully")
                return redirect('home')
            elif profile.user_type == "Seller" and profile.status == "Pending":
                messages.success(request, "Farmer verification Penfing,Try again after sometime.")
            elif profile.user_type == "Buyer":
                login(request, user)
                messages.success(request, "Logged in Successfully")
                return redirect('home')
        else:
            messages.success(request, "Invalid Credentials.")
    return render(request,'login.html')

def Admin_Login(request):
    error = ""
    if request.method == "POST":
        u = request.POST['uname']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        try:
            if user.is_staff:
                login(request, user)
                error = "yes"
            else:
                error = "not"
        except:
            error="not"
    d = {'error': error}
    return render(request,'loginadmin.html',d)


def Logout(request):
    logout(request)
    messages.success(request, 'Logout Successfully')
    return redirect('home')


def View_user(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    pro = Profile.objects.filter(user_type="Buyer")
    d = {'user':pro}
    return render(request,'view_user.html',d)

def View_farmer(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    pro = Profile.objects.filter(user_type="Seller")
    d = {'user':pro, 'data':'farmer'}
    return render(request,'view_user.html',d)


def Add_Product(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    cat = Category.objects.all()
    error=False
    if request.method=="POST":
        c = request.POST['cat']
        p = request.POST['pname']
        pr = request.POST['price']
        i = request.FILES['img']
        d = request.POST['desc']
        ct = Category.objects.get(name=c)
        Product.objects.create(category=ct, name=p, price=pr, image=i, desc=d, user=request.user)
        error=True
    d = {'cat': cat,'error':error}
    return render(request, 'add_product.html', d)


def All_product(request):
    if not request.user.is_authenticated:
        return redirect('login')
    user = User.objects.get(id=request.user.id)
    profile = Profile.objects.get(user=user)
    cart = Cart.objects.filter(profile=profile)
    num1=0
    for i in cart:
        num1 += 1
    cat = Category.objects.all()
    pro = Product.objects.all()
    d ={'pro':pro,'cat':cat,'num1':num1}
    return render(request,'all_product.html',d)


def Admin_View_Booking(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    book = Booking.objects.all()
    d = {'book': book}
    return render(request, 'admin_viewBokking.html', d)


def View_feedback(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    feed = Send_Feedback.objects.all()
    d = {'feed': feed}
    return render(request, 'view_feedback.html', d)


def View_prodcut(request,pid):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    cat = ""
    cat1 = ""
    pro1 = ""
    num1 = 0
    user=""
    profile=""
    cart=""
    pro=""
    num=""
    if not request.user.is_staff:
        user = User.objects.get(id=request.user.id)
        profile = Profile.objects.get(user=user)
        cart = Cart.objects.filter(profile=profile)
        for i in cart:
            num1 += 1

    if pid == 0:
        cat = "All Product"
        pro1 = Product.objects.all()
    else:
        cat1 = Category.objects.get(id=pid)
        pro1 = Product.objects.filter(category=cat1).all()
    cat = Category.objects.all()
    pro = Product.objects.all()
    num = []
    b = 1
    for j in cat:
        a = 1
        for i in pro:
            if j.name == i.category.name:
                if a == 1:
                    num.append(i.id)
                    a = 2
    d = {'pro': pro, 'cat': cat,'cat1': cat1,'num':num,'pro1':pro1,'num1':num1}
    return render(request, 'view_product.html',d)


def Add_Categary(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    error=False
    if request.method=="POST":
        n = request.POST['cat']
        Category.objects.create(name=n)
        error=True
    d = {'error':error}
    return render(request, 'add_category.html', d)


def View_Categary(request):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    pro = Category.objects.all()
    d = {'pro': pro}
    return render(request,'view_category.html', d)



def View_Booking(request):
    user = User.objects.get(id=request.user.id)
    profile = Profile.objects.get(user=user)
    cart = Cart.objects.filter(profile=profile)
    book = Booking.objects.filter(profile=profile)
    if profile.user_type == "Seller":
        book = Booking.objects.filter(farmer__icontains=request.user.username)
    pro = recommended_product(request)
    num1=0
    for i in cart:
        num1 += 1
    d = {'book': book,'num1':num1, 'pro':pro}
    return render(request, 'view_booking.html', d)


def Feedback(request, pid):
    if not request.user.is_authenticated:
        return redirect('login')
    error = False
    user1 = User.objects.get(id=request.user.id)
    profile = Profile.objects.get(user=user1)
    cart = Cart.objects.filter(profile=profile)
    num1 =0
    for i in cart:
        num1 += 1
    date1 = date.today()
    user = User.objects.get(id=pid)
    pro = Profile.objects.filter(user=user).first()
    if request.method == "POST":
        d = request.POST['date']
        u = request.POST['uname']
        e = request.POST['email']
        con = request.POST['contact']
        m = request.POST['desc']
        user = User.objects.filter(username=u, email=e).first()
        pro = Profile.objects.filter(user=user, contact=con).first()
        Send_Feedback.objects.create(profile=pro, date=d, message1=m)
        error = True
    d = {'pro': pro, 'date1': date1,'num1':num1,'error':error}

farmerapp/templates/add_product.html
{% extends 'navigation.html' %}
{% block body %}
{% load static %}
<div class="container">
    <h2 style="margin-top:20px" align="center">Add Product</h2><hr>

<div class="container-fluid" style="width:80%;margin-top:2%">
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Product Name</label>
      <input type="text" class="form-control" placeholder="Enter Product Name" name="pname" id="inputEmail4">
    </div>
    <div class="form-group col-md-6">
    <label for="exampleInputPassword1">Product Image</label>
    <input type="file" class="form-control" id="exampleInputPassword1" name="img" value="choose file">
</div></div>
    <div class="form-row">
        <div class="form-group col-md-6">
      <label for="inputState">Category</label>
      <select id="inputState" class="form-control" name="cat" required>
        <option>----Select Category----</option>
          {% for i in cat %}
        <option value="{{i.name}}">{{i.name}}</option>
          {% endfor %}
      </select>
    </div>

    <div class="form-group col-md-6">
      <label for="inputEmail4">Product Price</label>
      <input type="number" class="form-control" name="price" placeholder="Enter Price" id="inputEmail4">
    </div></div>
    <div class="form-group">
    <label for="exampleFormControlTextarea1">Description</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" name="desc" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</div>

{% if error %}
<script>
    alert('1 Product Added Successfully');
</script>
{% endif %}
{% endblock %}

farmerapp/templates/admin_view_product.html
{% extends 'navigation.html' %}
{% block body %}
<center><h2 style="color:red;margin-top:2%">View Product</h2></center><hr>
 <div class="container" style="margin-top:4%">
<table class="table table-bordered" id="myTable">
  <thead>
  <tr>
    <th>Product Name</th>
    <th>Image</th>
      <th> Category</th>
    <th>Price</th>
    <th> Description</th>
    {% if request.user.is_staff %}<th> Uploaded By</th>{% endif %}
    <th>Action</th>

  </tr>
  </thead>
   <tbody>

    {% for i in pro %}

  <tr>

    <td>{{i.name}}</td>
    <td><img src="{{i.image.url}}" style="width:50px;height:50px"></td>
      <td>{{i.category.name}}</td>
      <td>{{i.price}}</td>
      <td>{{i.desc}}</td>
      {% if request.user.is_staff %}<td>{{i.user.username}}</td>{% endif %}
    <td><a href="{% url 'delete_product' i.id %}" onclick="return confirm('Are you sure?')"><button class="button button1">Delete</button></a></td>

  </tr>

    {% endfor %}
    </tbody>
{{count}}
</table>

 </div>
<script>
  {% for i in message %}
  alert("{{i}}")
  {% endfor %}
</script>

{% endblock %}

farmerapp/templates/product_detail.html
{% extends 'navigation.html' %}
{% load static %}
{% load custom_tags %}
{% block body %}

<link rel = stylesheet href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

  <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>

  <!-- shop css -->
  <link href="{% static 'raw/css/shop.css' %}" type="text/css" rel="stylesheet" media="all">
  <link href="{% static 'raw/css/style.css' %}" type="text/css" rel="stylesheet" media="all">
  <link href="{% static 'raw/css/checkout.css' %}" type="text/css" rel="stylesheet" media="all">
  <!-- font-awesome icons -->
  <link href="{% static 'raw/css/font-awesome.css' %}" rel="stylesheet">
  <!-- //Custom Theme files -->
  <!-- online-fonts -->
  <!-- logo -->
  <link href="//fonts.googleapis.com/css?family=Fredericka+the+Great" rel="stylesheet">
  <!-- titles -->
  <link href="//fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i,700,700i,800,800i" rel="stylesheet">
  <!-- body -->
  <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">



<style>

  #example_length{
    text-align:left;
    margin-bottom:2%;
  }

  .dataTables_length{
    text-align:left;
  }

  .paginate_button{
      border:1px solid gray;
      padding:6px;
      cursor: pointer;
      color:white;
      background-color:green;
      margin:1px;
  }

  .dataTables_info{
    display:none;
  }

</style>


<div class="innerf-pages section">
    <div class="container">
  <div class="container">
    <h4 class="rad-txt">
        <span class="abtxt1">Product</span>
        <span class="abtext"> Details</span>
    </h4>
</div>
<div class="row">
      <div class="col-md-4">
            <div class="grid images_3_of_2">
                <div class="flexslider1">
                    <ul class="slides">
                        <li data-thumb="{{data.image.url}}">
                            <div class="thumb-image">
                                <img src="{{data.image.url}}" width="300" data-imagezoom="true" alt=" " class="img-responsive"> </div>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </div>

        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-6">
                <h3>{{data.name}}
                    <span></span>
                </h3>
            <p>by {{data.user.first_name}} {{data.user.last_name}}
                <a href="#">{{data.author}}</a>
            </p>
            <div class="caption">

                <ul class="rating-single">
                    <li>
                        <a href="#">
                            <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                        </a>
                    </li>
                </ul>
                <div class="clearfix"> </div>
                <h6>
                    Rs. {{data.price}}.00</h6>
            </div>
            <div class="desc_single">
                <h5>Description</h5>
                <p>{{data.desc}}</p>
            </div>

            
                <div class="occasional">
                    <h5>Specifications</h5>
                    <ul class="single_specific">
                        <li>
                            <span>Category :</span> {{data.category.name}}</li>
                        
                    </ul>

                </div>
                <br>
                <form align="center" action="{% url 'add_cart' data.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Add to Cart</button>
                </form>
            </div>
            <div class="col-md-6">
                <div class="occasional">
                    <h5>Farmer Contact Details</h5>

                    <ul class="single_specific">
                        {% if data.user.is_staff %}
                            <li>
                                <span>Product uploaded by admin</span>
                            </li>
                        {% else %}
                        <li>
                            <span>Name :</span> {{data.user.first_name}} {{data.user.last_name}}
                            <img  src="{{data.user.profile_set.all.0.image.url}}" style="width:100px">
                        </li>
                        <li>
                            <span>Mobile :</span> {{data.user.profile_set.all.0.contact}}</li>
                        <li>
                            <span>Email :</span> {{data.user.email}}</li>
                        <li>
                            <span>Address :</span> {{data.user.profile_set.all.0.address}}, {{data.user.profile_set.all.0.city}}</li>
                        
                      {% endif %}
                    </ul>

                </div>
            </div>
        </div>



          

            
            <div class="clearfix"></div>
        </div>
            
            <div class="occasion-cart">
                <div class="chr single-item single_page_b">
                    {% if data.user.id != request.user.id and data.user.is_staff %}
                    <form action="{% url 'add_cart' data.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="chr-cart pchr-cart">
                            <i class="fa fa-cart-plus" aria-hidden="true"></i> Add to cart</button>
                        <a href="#" data-toggle="modal" data-target="#myModal1"></a>
                    </form>
                    {% endif %}
                </div>
            </div>


        </div>
        <div class="clearfix"> </div>
        
        
        <div class="container" {% if request.user.profile_set.all.0.user_type == "Buyer" or data.status == "Booked" %} style="display:none"{% endif %}>
            <h4 class="rad-txt">
                <span class="abtxt1">seller</span>
                <span class="abtext"> comment</span>
            </h4>
        </div>
        
        <form method="post" action="" enctype="multipart/form-data" {% if request.user.profile_set.all.0.user_type == "Buyer" or data.status == "Booked" %} style="display:none"{% endif %}>
            {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Product Price</label>
                <input type="text" class="form-control" placeholder="Enter Product Price" name="pname" id="inputEmail4" required>
            </div>
            <div class="form-group col-md-6">
            <label for="exampleInputPassword1">Image</label>
            <input type="file" class="form-control" id="exampleInputPassword1" name="img" value="choose file" required>
    </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-12">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" name="desc" rows="3" required></textarea>
      </div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

<br>




<!-- /new_arrivals -->
<div class="section singlep_btm">
    <div class="container">
        <div class="new_arrivals">
            <h4 class="rad-txt">
                <span class="abtxt1">featured</span>
                <span class="abtext"> products</span>
            </h4>
            <!-- row3 -->
            {% for i in latest %}
                    <div class="col-md-3 product-men">
                        <div class="product-chr-info chr">
                            <div class="thumbnail">
                                <a href="{% url 'product_detail' i.id %}">
                                    <img src="{{i.image.url}}" alt="">
                                </a>
                            </div>
                            <div class="caption">
                                <h4>{{i.name}}</h4>
                                <p>{{i.author}}</p>
                                <div class="matrlf-mid">
                                    <ul class="rating">
                                        <li>
                                            <a href="#">
                                                <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="fa fa-star yellow-star" aria-hidden="true"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="fa fa-star gray-star" aria-hidden="true"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="fa fa-star gray-star" aria-hidden="true"></span>
                                            </a>
                                        </li>
                                    </ul>
                                    <ul class="price-list">
                                        <li>Status</li>
                                        <li>
                                            {{i.status}}
                                        </li>
                                    </ul>

                                    <div class="clearfix"> </div>
                                </div>
                                
                                
                                <a href="{% url 'product_detail' i.id %}">
                                    <button class="chr-cart pchr-cart">Contact to buyer
                                    </button>
                                </a>
                                
                                
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h4>No Any Product Available</h4>
                    {% endfor %}
            <!-- //row3 -->
            <div class="clearfix"></div>
        </div>
        <!--//new_arrivals-->
        <div class="clearfix"></div>

    </div>
</div>

<script>
    $(document).ready(function() {
        //Only needed for the filename of export files.
        //Normally set in the title tag of your page.
        document.title='Simple DataTable';
        // DataTable initialisation
        $('#example').DataTable(
            {
                "dom": '<"dt-buttons"Bf><"clear">lirtp',
                "paging": true,
                "autoWidth": true,
                "buttons": [
                    'colvis',
                    'copyHtml5',
            'csvHtml5',
                    'excelHtml5',
            'pdfHtml5',
                    'print'
                ]
            }
        );
    });
    </script>

{% endblock %}